/* =================
    KPIs_analysis
   ================= */
   
-- Q1: What is the total revenue generated?
select sum(total_sale) as total_revenue
from retailsales;


-- Q2: What is the total revenue generated each year?
select 
    Extract(year from sale_date)as sale_year, 
    Sum(total_sale) as total_revenue
from retailsales
    group by extract(year from sale_date)
order by sale_year;

-- Q3: What is the total revenue generated by each product category?
select category,sum(total_sale) as total_revenue
from retailsales
group by category
order by total_revenue desc;


-- Q4: What is the yearly revenue distribution across product categories?
select extract(year from sale_date) as sales_year,category,sum(total_sale) as total_revenue
from retailsales
group by extract(year from sale_date),category
order by sales_year,total_revenue desc;


-- Q5: Which customers have placed the highest number of orders?
select customer_id, count(r.transactions_id) order_count,sum(total_sale) as total_revenue
from retailsales r
group by customer_id
order by order_count desc;

-- Q6: Who are the top 10 customers based on total revenue contribution?
select customer_id, sum(total_sale) as total_revenue
from retailsales r
group by customer_id
order by total_revenue desc
fetch first 10 rows only;

-- Q7: Which product category has the highest quantity sold?
select category,sum(quantiy) as total_qty_sold
from retailsales
group by category;

-- Q8: What is the year-wise and month-wise distinct customer count? 
select 
    extract(year from sale_date) as sales_year,
    extract(month from sale_date) as sales_month,
    count(distinct customer_id) as cust_count
from retailsales 
group by 
    extract(year from sale_date),
    extract(month from sale_date)
order by sales_year,cust_count desc;